---- MODULE TestFsm_xstate ----
(*
 * .planning/formal/tla/TestFsm_xstate.tla
 * GENERATED by bin/fsm-to-tla.cjs
 * Source: test.ts
 * Regenerate: node bin/fsm-to-tla.cjs test.ts --module=TestFsm
 * Generated: 2026-06-29
 *
 * Machine id: test-fsm
 * Framework:  xstate-v5
 * Initial state:     idle
 * States (3):          idle, running, done
 * Final states:      done
*)
EXTENDS Naturals, FiniteSets, TLC

\* ── Constants (model-checking bounds) ────────────────────────────────────────
CONSTANTS MaxBound  \* upper bound for event parameter quantifiers

\* ── Variables ────────────────────────────────────────────────────────────────
VARIABLES
    state,  \* FSM state
    count  \* default: 0  annotation: (no annotation)

vars == <<state, count>>

\* ── Type invariant ────────────────────────────────────────────────────────────
\* @requirement QUORUM-01
TypeOK ==
    /\ state \in {"idle", "running", "done"}
    /\ count \in Nat  \* FIXME: tighten bound if needed

\* ── Initial state ─────────────────────────────────────────────────────────────
Init ==
    /\ state = "idle"
    /\ count = 0

\* ── Actions ────────────────────────────────────────────────────────────────────

\* idle -[START]-> running
Start ==
    /\ state = "idle"
    /\ state' = "running"
    /\ UNCHANGED count

\* running -[FINISH / isReady]-> done
Finish ==
    /\ state = "running"
    /\ TRUE  \* FIXME: guard isReady — add to config guards
    /\ state' = "done"
    /\ count' = count  \* FIXME: XState assign for count

\* done is a final (absorbing) state
Staydone ==
    /\ state = "done"
    /\ state' = "done"
    /\ UNCHANGED <<count>>

\* ── Next ──────────────────────────────────────────────────────────────────────
Next ==
    \/ Start
    \/ Finish
    \/ Staydone

\* ── Specification ─────────────────────────────────────────────────────────────
Spec == Init /\ [][Next]_vars

\* ── Invariants (add domain-specific properties here) ──────────────────────────
\* TypeOK is the structural baseline. Add semantic invariants below.

====
